
use std::sync::{Arc, Mutex};
use serde::{Deserialize, Serialize};
use crate::error::ReferralError;
use crate::models::request::CreateRefRequest;
use crate::repositories::ReferralRepository;

pub struct Services {
    pub referral_service: Arc<Mutex<ReferralService>>,
}


#[derive(Clone)]
pub struct ReferralService {
    repository: Arc<Mutex<ReferralRepository>>,
}

#[derive(Clone, Serialize, Deserialize)]
pub struct RefCode{
    ref_code: String
}
impl ReferralService {
    pub fn new(repository: Arc<Mutex<ReferralRepository>>) -> Self {
        Self { repository }
    }

    pub async fn create_ref(
        &self,
        req: CreateRefRequest,
    ) -> Result<(), ReferralError> {
        //first we need to check if the code has been already generated by this user
        match self.repository.lock() {
            Ok(repository) => Ok(repository.create_ref(req).await?),
            Err(_) => Err(ReferralError::InternalError),
        }
    }




}
