version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: referral_db
    ports:
      - "5434:5432" # Map PostgreSQL port to the host
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist data
    networks:
      - app-network

  referral-generation-service:
    container_name: referral-generation-service
    build:
      context: ./referral-generation-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081" # Map the service port to the host
    environment:
      - DATABASE_URL=postgres://admin:password@postgres:5432/referral_db
      - RUST_LOG=INFO
    depends_on:
      - postgres # Ensure PostgreSQL starts first
    networks:
      - app-network

  referral-claiming-service:
    container_name: referral-claiming-service
    build:
      context: ./referral-claiming-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082" # Map the service port to the host
    environment:
      - DATABASE_URL=postgres://admin:password@postgres:5432/referral_db
      - RUST_LOG=INFO
    depends_on:
      - postgres # Ensure PostgreSQL starts first
    networks:
      - app-network

  referral-query-service:
    container_name: referral-query-service
    build:
      context: ./referral-query-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083" # Map the service port to the host
    environment:
      - DATABASE_URL=postgres://admin:password@postgres:5432/referral_db
      - RUST_LOG=INFO
    depends_on:
      - postgres # Ensure PostgreSQL starts first
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge